### ISSUE TITLE
can't open zipped file

### ISSUE THREAD

**Issue by preludem** [rcdmk/aspZip#7] opened 2019-12-14 19:24 UTC
Hello. İ'm trying to use this script on windows server 2012 r2 and windows 8.1 but there is an error. I did to zip the files. However, when I click on the zip file, it does not open and gives an error. Also, I cannot delete the zipped file and move it to another location. Please help me with the error. I really need this script.

**Comment by rcdmk** [comment] 2019-12-14 20:50
Hi. It should work properly on a Windows Server 2012 r2, but I did't test it on a Windows 8.1 PC yet.
The fact that you can't move or delete the file indicates it may still be open by some process, that need to be finished first. This can be caused by a hanging upload or a some other program opening the file while you are trying to compress it.

For instance, if you are trying to compress a file that some process is constantly writing to it, like a log file, you will have to stop the writing on that file before trying to compress it.

Try compressing other files that you are sure they will not be open on other processes to see if it works.

Also, some times, when uploading files to a Windows server for a classic ASP application, some of the files get stuck that way, uploading only a portion of the file and then I wasn't able to open, move or delete it through FTP. The only way I managed to delete them was to login on the server and delete it there, with a RDP connection.

**Comment by rcdmk** [comment] 2024-04-30 06:46
I know this is very old, but it should probably be better now with version 0.4.

**Comment by rcdmk** [comment] 2024-05-09 05:01
I'll close this issue with the hope that it is solved, but please feel free to reopen if the issue persists.

**Closed as completed by rcdmk** 2024-05-09 05:01 UTC
Labels: question
